# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/nfs/homes/mbenmesb/Documents/my_minishell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/nfs/homes/mbenmesb/Documents/my_minishell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/nfs/homes/mbenmesb/Documents/my_minishell/CMakeFiles /mnt/nfs/homes/mbenmesb/Documents/my_minishell//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/nfs/homes/mbenmesb/Documents/my_minishell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_minishell

# Build rule for target.
my_minishell: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_minishell
.PHONY : my_minishell

# fast build rule for target.
my_minishell/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/build
.PHONY : my_minishell/fast

srcs/check_validity_of_line_input.o: srcs/check_validity_of_line_input.c.o
.PHONY : srcs/check_validity_of_line_input.o

# target to build an object file
srcs/check_validity_of_line_input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/check_validity_of_line_input.c.o
.PHONY : srcs/check_validity_of_line_input.c.o

srcs/check_validity_of_line_input.i: srcs/check_validity_of_line_input.c.i
.PHONY : srcs/check_validity_of_line_input.i

# target to preprocess a source file
srcs/check_validity_of_line_input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/check_validity_of_line_input.c.i
.PHONY : srcs/check_validity_of_line_input.c.i

srcs/check_validity_of_line_input.s: srcs/check_validity_of_line_input.c.s
.PHONY : srcs/check_validity_of_line_input.s

# target to generate assembly for a file
srcs/check_validity_of_line_input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/check_validity_of_line_input.c.s
.PHONY : srcs/check_validity_of_line_input.c.s

srcs/display_error.o: srcs/display_error.c.o
.PHONY : srcs/display_error.o

# target to build an object file
srcs/display_error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/display_error.c.o
.PHONY : srcs/display_error.c.o

srcs/display_error.i: srcs/display_error.c.i
.PHONY : srcs/display_error.i

# target to preprocess a source file
srcs/display_error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/display_error.c.i
.PHONY : srcs/display_error.c.i

srcs/display_error.s: srcs/display_error.c.s
.PHONY : srcs/display_error.s

# target to generate assembly for a file
srcs/display_error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/display_error.c.s
.PHONY : srcs/display_error.c.s

srcs/executor.o: srcs/executor.c.o
.PHONY : srcs/executor.o

# target to build an object file
srcs/executor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/executor.c.o
.PHONY : srcs/executor.c.o

srcs/executor.i: srcs/executor.c.i
.PHONY : srcs/executor.i

# target to preprocess a source file
srcs/executor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/executor.c.i
.PHONY : srcs/executor.c.i

srcs/executor.s: srcs/executor.c.s
.PHONY : srcs/executor.s

# target to generate assembly for a file
srcs/executor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/executor.c.s
.PHONY : srcs/executor.c.s

srcs/get_data_token.o: srcs/get_data_token.c.o
.PHONY : srcs/get_data_token.o

# target to build an object file
srcs/get_data_token.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/get_data_token.c.o
.PHONY : srcs/get_data_token.c.o

srcs/get_data_token.i: srcs/get_data_token.c.i
.PHONY : srcs/get_data_token.i

# target to preprocess a source file
srcs/get_data_token.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/get_data_token.c.i
.PHONY : srcs/get_data_token.c.i

srcs/get_data_token.s: srcs/get_data_token.c.s
.PHONY : srcs/get_data_token.s

# target to generate assembly for a file
srcs/get_data_token.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/get_data_token.c.s
.PHONY : srcs/get_data_token.c.s

srcs/get_path.o: srcs/get_path.c.o
.PHONY : srcs/get_path.o

# target to build an object file
srcs/get_path.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/get_path.c.o
.PHONY : srcs/get_path.c.o

srcs/get_path.i: srcs/get_path.c.i
.PHONY : srcs/get_path.i

# target to preprocess a source file
srcs/get_path.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/get_path.c.i
.PHONY : srcs/get_path.c.i

srcs/get_path.s: srcs/get_path.c.s
.PHONY : srcs/get_path.s

# target to generate assembly for a file
srcs/get_path.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/get_path.c.s
.PHONY : srcs/get_path.c.s

srcs/lst_token.o: srcs/lst_token.c.o
.PHONY : srcs/lst_token.o

# target to build an object file
srcs/lst_token.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/lst_token.c.o
.PHONY : srcs/lst_token.c.o

srcs/lst_token.i: srcs/lst_token.c.i
.PHONY : srcs/lst_token.i

# target to preprocess a source file
srcs/lst_token.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/lst_token.c.i
.PHONY : srcs/lst_token.c.i

srcs/lst_token.s: srcs/lst_token.c.s
.PHONY : srcs/lst_token.s

# target to generate assembly for a file
srcs/lst_token.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/lst_token.c.s
.PHONY : srcs/lst_token.c.s

srcs/main.o: srcs/main.c.o
.PHONY : srcs/main.o

# target to build an object file
srcs/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/main.c.o
.PHONY : srcs/main.c.o

srcs/main.i: srcs/main.c.i
.PHONY : srcs/main.i

# target to preprocess a source file
srcs/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/main.c.i
.PHONY : srcs/main.c.i

srcs/main.s: srcs/main.c.s
.PHONY : srcs/main.s

# target to generate assembly for a file
srcs/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/main.c.s
.PHONY : srcs/main.c.s

srcs/setting_redirections.o: srcs/setting_redirections.c.o
.PHONY : srcs/setting_redirections.o

# target to build an object file
srcs/setting_redirections.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/setting_redirections.c.o
.PHONY : srcs/setting_redirections.c.o

srcs/setting_redirections.i: srcs/setting_redirections.c.i
.PHONY : srcs/setting_redirections.i

# target to preprocess a source file
srcs/setting_redirections.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/setting_redirections.c.i
.PHONY : srcs/setting_redirections.c.i

srcs/setting_redirections.s: srcs/setting_redirections.c.s
.PHONY : srcs/setting_redirections.s

# target to generate assembly for a file
srcs/setting_redirections.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/setting_redirections.c.s
.PHONY : srcs/setting_redirections.c.s

srcs/shell_lexer.o: srcs/shell_lexer.c.o
.PHONY : srcs/shell_lexer.o

# target to build an object file
srcs/shell_lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/shell_lexer.c.o
.PHONY : srcs/shell_lexer.c.o

srcs/shell_lexer.i: srcs/shell_lexer.c.i
.PHONY : srcs/shell_lexer.i

# target to preprocess a source file
srcs/shell_lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/shell_lexer.c.i
.PHONY : srcs/shell_lexer.c.i

srcs/shell_lexer.s: srcs/shell_lexer.c.s
.PHONY : srcs/shell_lexer.s

# target to generate assembly for a file
srcs/shell_lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/shell_lexer.c.s
.PHONY : srcs/shell_lexer.c.s

srcs/shell_parser.o: srcs/shell_parser.c.o
.PHONY : srcs/shell_parser.o

# target to build an object file
srcs/shell_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/shell_parser.c.o
.PHONY : srcs/shell_parser.c.o

srcs/shell_parser.i: srcs/shell_parser.c.i
.PHONY : srcs/shell_parser.i

# target to preprocess a source file
srcs/shell_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/shell_parser.c.i
.PHONY : srcs/shell_parser.c.i

srcs/shell_parser.s: srcs/shell_parser.c.s
.PHONY : srcs/shell_parser.s

# target to generate assembly for a file
srcs/shell_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/shell_parser.c.s
.PHONY : srcs/shell_parser.c.s

srcs/struct_init_lexer.o: srcs/struct_init_lexer.c.o
.PHONY : srcs/struct_init_lexer.o

# target to build an object file
srcs/struct_init_lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/struct_init_lexer.c.o
.PHONY : srcs/struct_init_lexer.c.o

srcs/struct_init_lexer.i: srcs/struct_init_lexer.c.i
.PHONY : srcs/struct_init_lexer.i

# target to preprocess a source file
srcs/struct_init_lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/struct_init_lexer.c.i
.PHONY : srcs/struct_init_lexer.c.i

srcs/struct_init_lexer.s: srcs/struct_init_lexer.c.s
.PHONY : srcs/struct_init_lexer.s

# target to generate assembly for a file
srcs/struct_init_lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/struct_init_lexer.c.s
.PHONY : srcs/struct_init_lexer.c.s

srcs/struct_init_parser.o: srcs/struct_init_parser.c.o
.PHONY : srcs/struct_init_parser.o

# target to build an object file
srcs/struct_init_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/struct_init_parser.c.o
.PHONY : srcs/struct_init_parser.c.o

srcs/struct_init_parser.i: srcs/struct_init_parser.c.i
.PHONY : srcs/struct_init_parser.i

# target to preprocess a source file
srcs/struct_init_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/struct_init_parser.c.i
.PHONY : srcs/struct_init_parser.c.i

srcs/struct_init_parser.s: srcs/struct_init_parser.c.s
.PHONY : srcs/struct_init_parser.s

# target to generate assembly for a file
srcs/struct_init_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/struct_init_parser.c.s
.PHONY : srcs/struct_init_parser.c.s

srcs/tokenize.o: srcs/tokenize.c.o
.PHONY : srcs/tokenize.o

# target to build an object file
srcs/tokenize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/tokenize.c.o
.PHONY : srcs/tokenize.c.o

srcs/tokenize.i: srcs/tokenize.c.i
.PHONY : srcs/tokenize.i

# target to preprocess a source file
srcs/tokenize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/tokenize.c.i
.PHONY : srcs/tokenize.c.i

srcs/tokenize.s: srcs/tokenize.c.s
.PHONY : srcs/tokenize.s

# target to generate assembly for a file
srcs/tokenize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/tokenize.c.s
.PHONY : srcs/tokenize.c.s

srcs/update_free_memory.o: srcs/update_free_memory.c.o
.PHONY : srcs/update_free_memory.o

# target to build an object file
srcs/update_free_memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/update_free_memory.c.o
.PHONY : srcs/update_free_memory.c.o

srcs/update_free_memory.i: srcs/update_free_memory.c.i
.PHONY : srcs/update_free_memory.i

# target to preprocess a source file
srcs/update_free_memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/update_free_memory.c.i
.PHONY : srcs/update_free_memory.c.i

srcs/update_free_memory.s: srcs/update_free_memory.c.s
.PHONY : srcs/update_free_memory.s

# target to generate assembly for a file
srcs/update_free_memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/update_free_memory.c.s
.PHONY : srcs/update_free_memory.c.s

srcs/utils.o: srcs/utils.c.o
.PHONY : srcs/utils.o

# target to build an object file
srcs/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/utils.c.o
.PHONY : srcs/utils.c.o

srcs/utils.i: srcs/utils.c.i
.PHONY : srcs/utils.i

# target to preprocess a source file
srcs/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/utils.c.i
.PHONY : srcs/utils.c.i

srcs/utils.s: srcs/utils.c.s
.PHONY : srcs/utils.s

# target to generate assembly for a file
srcs/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_minishell.dir/build.make CMakeFiles/my_minishell.dir/srcs/utils.c.s
.PHONY : srcs/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... my_minishell"
	@echo "... srcs/check_validity_of_line_input.o"
	@echo "... srcs/check_validity_of_line_input.i"
	@echo "... srcs/check_validity_of_line_input.s"
	@echo "... srcs/display_error.o"
	@echo "... srcs/display_error.i"
	@echo "... srcs/display_error.s"
	@echo "... srcs/executor.o"
	@echo "... srcs/executor.i"
	@echo "... srcs/executor.s"
	@echo "... srcs/get_data_token.o"
	@echo "... srcs/get_data_token.i"
	@echo "... srcs/get_data_token.s"
	@echo "... srcs/get_path.o"
	@echo "... srcs/get_path.i"
	@echo "... srcs/get_path.s"
	@echo "... srcs/lst_token.o"
	@echo "... srcs/lst_token.i"
	@echo "... srcs/lst_token.s"
	@echo "... srcs/main.o"
	@echo "... srcs/main.i"
	@echo "... srcs/main.s"
	@echo "... srcs/setting_redirections.o"
	@echo "... srcs/setting_redirections.i"
	@echo "... srcs/setting_redirections.s"
	@echo "... srcs/shell_lexer.o"
	@echo "... srcs/shell_lexer.i"
	@echo "... srcs/shell_lexer.s"
	@echo "... srcs/shell_parser.o"
	@echo "... srcs/shell_parser.i"
	@echo "... srcs/shell_parser.s"
	@echo "... srcs/struct_init_lexer.o"
	@echo "... srcs/struct_init_lexer.i"
	@echo "... srcs/struct_init_lexer.s"
	@echo "... srcs/struct_init_parser.o"
	@echo "... srcs/struct_init_parser.i"
	@echo "... srcs/struct_init_parser.s"
	@echo "... srcs/tokenize.o"
	@echo "... srcs/tokenize.i"
	@echo "... srcs/tokenize.s"
	@echo "... srcs/update_free_memory.o"
	@echo "... srcs/update_free_memory.i"
	@echo "... srcs/update_free_memory.s"
	@echo "... srcs/utils.o"
	@echo "... srcs/utils.i"
	@echo "... srcs/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

